---
title: "fMRI"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
author: "Ludovica Nucci (Start 23/03/2020; language: it)"
output: 
  html_document: 
    fig_height: 7
    fig_width: 10
    highlight: tango
    theme: cerulean
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r preamble, message=FALSE, warning=FALSE}
library(rstudioapi)
cat("\f")
rm(list=ls())
current_path <- getActiveDocumentContext()$path
setwd(dirname(current_path )); print(getwd())

library(sysid)
library(MTS)
```


```{r DATI}
lf=read.table("./tfMRI_MOTOR_LR/lf_100206.txt", sep="\t") 
rf=read.table("./tfMRI_MOTOR_LR/rf_100206.txt", sep="\t")
rh=read.table("./tfMRI_MOTOR_LR/rh_100206.txt", sep="\t")
lh=read.table("./tfMRI_MOTOR_LR/lh_100206.txt", sep="\t")
t=read.table("./tfMRI_MOTOR_LR/t_100206.txt", sep="\t")
#la risonanza magnetica acquisisce un'immagine ogni 0.72s, 12s è la durata di ciascun task motorio, la prima immagine è acquisita al tempo 0
# 1=motion 0=resting 
X=rep(0,284)#Serie temporale degli stimoli
X[(ceiling(lf[1,1]/0.72)+1) : (floor((lf[1,1]+12)/0.72)+1)]=1
X[(ceiling(lf[2,1]/0.72)+1) : (floor((lf[2,1]+12)/0.72)+1)]=1
X[(ceiling(rf[1,1]/0.72)+1) : (floor((rf[1,1]+12)/0.72)+1)]=1
X[(ceiling(rf[2,1]/0.72)+1) : (floor((rf[2,1]+12)/0.72)+1)]=1
X[(ceiling(rh[1,1]/0.72)+1) : (floor((rh[1,1]+12)/0.72)+1)]=1
X[(ceiling(rh[2,1]/0.72)+1) : (floor((rh[2,1]+12)/0.72)+1)]=1
X[(ceiling(lh[1,1]/0.72)+1) : (floor((lh[1,1]+12)/0.72)+1)]=1
X[(ceiling(lh[2,1]/0.72)+1) : (floor((lh[2,1]+12)/0.72)+1)]=1
X[(ceiling(t[1,1]/0.72)+1) : (floor((t[1,1]+12)/0.72)+1)]=1
X[(ceiling(t[2,1]/0.72)+1) : (floor((t[2,1]+12)/0.72)+1)]=1

ts=0.72 #Sampling time interval
out_order=2 #Number of output delays
in_order=2 #Number of input delays
max_order=max(out_order, in_order)
comp_nr = 5 #Number of connectivity component

#Activation thresholds (Critical values of F-Statistics)
act_thresh=qf(.99, df1=in_order, df2=(284-max_order-(in_order+out_order)))
act_thresh_CONN=qf(.99, df1 =in_order, df2= (284-max_order-1-(out_order+(in_order*(comp_nr+1))))) 

load("~/TESI/tfMRI_MOTOR_LR/sub_100206.RData")
dataMatrix=ar_100206[-c(1,2,3),] 
#la matrice dataMatrix contiene per colonna le serie temporali dei voxel del soggetto 100206
```

```{r ACTIVATION DETECTION THROUGH GRANGER CAUSALITY}
#(~17 min)

Activation_base <- function(X, Y, in_order, out_order, ts){
  #AR model for the time serie Y
  ARmodel=ar(Y, aic = FALSE, order.max = out_order) #Y[n]=ARmodel$ar[1]*Y[n-1]+ARmodel$ar[2]*Y[n-2]+ARmodel$resid[n]
  RSS_AR=sum(ARmodel$resid[(max_order+1):284]^2)
  #ARX model for the pair [X Y]
  data=idframe(Y, X , Ts = ts, start = 0, unit = "seconds")
  ARXmodel=arx(data, order = c(out_order, in_order, 1), lambda = 1, intNoise = FALSE, fixed = NULL )
  res_ARX= Y[(max_order+1):284]-ARXmodel$fitted.values[(max_order+1):284]
  #ARXmodel$fitted.values[n]=-(ARXmodel$sys$A[2]*Y[n-1]+ARXmodel$sys$A[3]*Y[n-2])+ARXmodel$sys$B[1]*st[n-1]+ARXmodel$sys$B[2]*st[n-2]
  RSS_ARX=sum(res_ARX^2)
  
  ((RSS_AR - RSS_ARX)/RSS_ARX) * ((284-max_order-(in_order+out_order))/in_order) 
  #F-statistica ~F(in_order , 284-max_order-(in_order+out_order)) 
}
  
act=rep(0, dim(dataMatrix)[2])
for (i in 1:dim(dataMatrix)[2]) {
    Y_temp = dataMatrix[,i]
    Y = Y_temp - mean(Y_temp)
    act[i]=Activation_base(X, Y, in_order, out_order, ts)
}

#save(act, file = "./tfMRI_MOTOR_LR/act_in=2_out=2.RData")   
#load("~/TESI/tfMRI_MOTOR_LR/act_in=2_out=2.RData")
```

```{r DETECTION OF MAXIMALLY CAUSED VOXEL WITH RESPECT TO EACH VOXEL}
#(~25 min .995 ~1h 45 min .99)
CONN_matr=c()
CONN_matr_gr=c()
for (i in 1:length(which(act>act_thresh))) {
  act_idx=which(act>act_thresh)[-i]
  conn_temp = c()
  for (j in 1:length(act_idx)) {
     conn_temp=rbind(conn_temp, c(Activation_base(dataMatrix[,act_idx[j]], dataMatrix[,which(act>act_thresh)[i]], in_order, out_order, ts), act_idx[j]))
     #conn_temp è una matrice "# di voxel attivati" x 2 -> alla riga j_esima abbiamo, nella prima colonna il valore di Granger tra il j_esimo voxel e l'i_esimo, nella seconda il numero della colonna che il j_esimo voxel occupa in dataMatrix
  }
  ord=order(conn_temp[,1], decreasing = TRUE)
  conn_temp=conn_temp[ord,] #nelle prime righe i voxel che hanno causalità di Granger più alta rispetto al voxel i_esimo
  conn_temp2 = conn_temp[1:comp_nr,2]
  CONN_matr = cbind( CONN_matr, c(which(act>act_thresh)[i], conn_temp2))
  #CONN_matr è la matrice (comp_nr+1) x (# voxel attivati) che nella i_esima colonna ha il numero della colonna che l' i_esimo voxel attivato occupa in dataMatrix e i numeri delle colonne dei voxel attivati che hanno causalità più alta rispetto all'i_esimo  
  conn_temp1 = conn_temp[1:comp_nr,1]
  CONN_matr_gr = cbind(CONN_matr_gr, c(which(act>act_thresh)[i], conn_temp1))
  #CONN_matr_gr è la matrice (comp_nr+1) x (# voxel attivati) che nella i_esima colonna ha il numero della colonna che l'i_esimo voxel attivato occupa in dataMatrix e i valori di Granger tra "i voxel attivati che hanno causalità più alta rispetto all'i_esimo" e "l'i_esimo voxel"
}

#save(CONN_matr, file = "./tfMRI_MOTOR_LR/CONN_matr_in=2_out=2_.99.RData")   
#save(CONN_matr_gr, file = "./tfMRI_MOTOR_LR/CONN_matr_gr_in=2_out=2_.99.RData")  
#load("~/TESI/tfMRI_MOTOR_LR/CONN_matr_in=2_out=2_.99.RData")
#load("~/TESI/tfMRI_MOTOR_LR/CONN_matr_gr_in=2_out=2_.99.RData")
```

```{r ACTIVATION DETECTION THROUGH CONNECTIVITY}

Activation<- function(X, Y, CONN, in_order, out_order, ts){
  #ARX model for the time series Y CONN
  ARXmodel_red=VARX(Y[2:284], out_order, xt = CONN[1:283,], m = (in_order-1), include.mean = F, fixed = NULL)
  #Y[n]-(ARXmodel_red$coef[1]*Y[n-1]+ARXmodel_red$coef[2]*Y[n-2]+ARXmodel_red$coef[3]*CONN[n-1,1]+ARXmodel_red$coef[4]*CONN[n-1,2]+ARXmodel_red$coef[5]*CONN[n-1,3]+ARXmodel_red$coef[6]*CONN[n-1,4]+ARXmodel_red$coef[7]*CONN[n-2,1]+ARXmodel_red$coef[8]*CONN[n-2,2]+ARXmodel_red$coef[9]*CONN[n-2,3]+ARXmodel_red$coef[10]*CONN[n-2,4])=ARXmodel_red$residuals[n-3] n>3
  RSS_red=sum(ARXmodel_red$residuals^2)
  #ARX model for [X CONN Y]
  ARXmodel_full=VARX(Y[2:284], out_order, xt = cbind(X[1:283],CONN[1:283,]), m = (in_order-1), include.mean = F, fixed= NULL)
  RSS_full=sum(ARXmodel_full$residuals^2)
 
  ((RSS_red - RSS_full)/RSS_full) *((284-max_order-1 -(out_order+ (in_order*(comp_nr+1))))/(in_order))
  #F-statistica ~F(in_order , 284-max_order-1 -(out_order+ (in_order*(comp_nr+1))) )
}

act_CONN = rep(0,length(which(act>act_thresh)))
for (i in 1:length(which(act>act_thresh))){
  Y_temp = dataMatrix[,which(act>act_thresh)[i]]
  Y = Y_temp - mean(Y_temp)
  CONN=dataMatrix[, CONN_matr[-1,i]] #CONN è una matrice 284 x comp_nr dove ogni colonna è la serie temporale di un voxel con alta causalità di Granger rispetto a quello in esame
  act_CONN[i]=Activation(X, Y, CONN, in_order, out_order, ts)
}

#length(which(act > act_thresh)) .99 ->1055
#length(which(act_CONN> act_thresh_CONN)) .99 ->865
```



